allow-overwrite=true
auto-file-renaming=true
bt-detach-seed-only=true
bt-enable-lpd=false
bt-remove-unselected-file=true
check-certificate=false
check-integrity=false
continue=true
content-disposition-default-utf8=true
daemon=true

disk-cache=0M
rpc-max-request-size=10M

enable-rpc=true
follow-torrent=mem
force-save=true
http-accept-gzip=true
max-connection-per-server=4
max-concurrent-downloads=2
split=4
max-file-not-found=0
max-tries=10
min-split-size=20M

netrc-path=/usr/src/app/.netrc
optimize-concurrent-downloads=false
peer-id-prefix=-qB4430-
peer-agent=qBittorrent/4.4.3
quiet=true
reuse-uri=true
seed-ratio=0
summary-interval=0
user-agent=Wget/1.12
